# DATA CLEANING PREPROCESSING
> : data cleaning basics




> : handling missing values





> : data exploration

Installing Library Required

In [ ]:
import pandas as pd
import datetime as dt
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
df = pd.read_csv('all_data.csv')
df.head(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
6,176562,USB-C Charging Cable,1,11.95,04/29/19 13:03,"381 Wilson St, San Francisco, CA 94016"
7,176563,Bose SoundSport Headphones,1,99.99,04/02/19 07:46,"668 Center St, Seattle, WA 98101"
8,176564,USB-C Charging Cable,1,11.95,04/12/19 10:58,"790 Ridge St, Atlanta, GA 30301"
9,176565,Macbook Pro Laptop,1,1700,04/24/19 10:38,"915 Willow St, San Francisco, CA 94016"

**EXPLORING DATASET**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186850 entries, 0 to 186849
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          186305 non-null  object
 1   Product           186305 non-null  object
 2   Quantity Ordered  186305 non-null  object
 3   Price Each        186305 non-null  object
 4   Order Date        186305 non-null  object
 5   Purchase Address  186305 non-null  object
dtypes: object(6)
memory usage: 8.6+ MB

We will now handle the following data cleaning steps:

*   **Check for Nulls**: Identify and address any missing values in the dataset.
*   **Handle Datatype of Features**: Convert columns to their appropriate data types (e.g., numeric, datetime).
*   **Separate Columns**: Extract relevant information from existing columns into new, more usable features.

In [ ]:
df.isna().sum()             #   check for null values

Order ID            545
Product             545
Quantity Ordered    545
Price Each          545
Order Date          545
Purchase Address    545
dtype: int64

In [ ]:
df[df.isna().any(axis=1)]                 # rows which are null

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
1,NaN,NaN,NaN,NaN,NaN,NaN
356,NaN,NaN,NaN,NaN,NaN,NaN
735,NaN,NaN,NaN,NaN,NaN,NaN
1433,NaN,NaN,NaN,NaN,NaN,NaN
1553,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
185176,NaN,NaN,NaN,NaN,NaN,NaN
185438,NaN,NaN,NaN,NaN,NaN,NaN
186042,NaN,NaN,NaN,NaN,NaN,NaN
186548,NaN,NaN,NaN,NaN,NaN,NaN
186826,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.dropna(axis = 0 , inplace = True)    # dropping nulls because they are less compared to dataset size

In [ ]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.reset_index(inplace = True)                # fixing the index numbering and dropping column 'index'

In [ ]:
df = df.drop(columns = 'index')

In [ ]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
2,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
3,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"

changing datatypes

In [ ]:
df = df[df['Order ID'] != 'Order ID']
df = df.astype({'Order ID':'int','Quantity Ordered':'int','Price Each':'float'})
df['Order Date'] = pd.to_datetime(df['Order Date'])

/tmp/ipython-input-2054589813.py:3: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185686 entries, 0 to 185686
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          185686 non-null  int64
 1   Product           185686 non-null  object
 2   Quantity Ordered  185686 non-null  int64
 3   Price Each        185686 non-null  float64
 4   Order Date        185686 non-null  datetime64[ns]
 5   Purchase Address  185686 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 9.9+ MB

In [ ]:
df.head(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,2019-04-19 08:46:00,"917 1st St, Dallas, TX 75001"
1,176559,Bose SoundSport Headphones,1,99.99,2019-04-07 22:30:00,"682 Chestnut St, Boston, MA 02215"
2,176560,Google Phone,1,600.00,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001"
3,176560,Wired Headphones,1,11.99,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001"
4,176561,Wired Headphones,1,11.99,2019-04-30 09:27:00,"333 8th St, Los Angeles, CA 90001"
5,176562,USB-C Charging Cable,1,11.95,2019-04-29 13:03:00,"381 Wilson St, San Francisco, CA 94016"
6,176563,Bose SoundSport Headphones,1,99.99,2019-04-02 07:46:00,"668 Center St, Seattle, WA 98101"
7,176564,USB-C Charging Cable,1,11.95,2019-04-12 10:58:00,"790 Ridge St, Atlanta, GA 30301"
8,176565,Macbook Pro Laptop,1,1700.00,2019-04-24 10:38:00,"915 Willow St, San Francisco, CA 94016"
9,176566,Wired Headphones,1,11.99,2019-04-08 14:05:00,"83 7th St, Boston, MA 02215"

**Data Exploration**
> : Extract relevant information from 'Order Date'

> : Create New Feature (Total sales)

> : Analyze Monthly Sales

> : Identify Top-Selling Products AND Worst Performing

### Separate time and date from order date

In [ ]:
df['Date'] = df['Order Date'].dt.date
df['Time'] = df['Order Date'].dt.time
df.drop(columns=['Order Date','Purchase Address'],inplace = True)
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Date,Time
0,176558,USB-C Charging Cable,2,11.95,2019-04-19,08:46:00
1,176559,Bose SoundSport Headphones,1,99.99,2019-04-07,22:30:00
2,176560,Google Phone,1,600.00,2019-04-12,14:38:00
3,176560,Wired Headphones,1,11.99,2019-04-12,14:38:00
4,176561,Wired Headphones,1,11.99,2019-04-30,09:27:00

### Creating Total Sales Column

In [ ]:
df['Total Sales'] = df['Quantity Ordered'] * df['Price Each']
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Date,Time,Total Sales
0,176558,USB-C Charging Cable,2,11.95,2019-04-19,08:46:00,23.90
1,176559,Bose SoundSport Headphones,1,99.99,2019-04-07,22:30:00,99.99
2,176560,Google Phone,1,600.00,2019-04-12,14:38:00,600.00
3,176560,Wired Headphones,1,11.99,2019-04-12,14:38:00,11.99
4,176561,Wired Headphones,1,11.99,2019-04-30,09:27:00,11.99

## Calculate Monthly Sales

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Date,Time,Total Sales,Month
0,176558,USB-C Charging Cable,2,11.95,2019-04-19,08:46:00,23.90,4
1,176559,Bose SoundSport Headphones,1,99.99,2019-04-07,22:30:00,99.99,4
2,176560,Google Phone,1,600.00,2019-04-12,14:38:00,600.00,4
3,176560,Wired Headphones,1,11.99,2019-04-12,14:38:00,11.99,4
4,176561,Wired Headphones,1,11.99,2019-04-30,09:27:00,11.99,4

In [ ]:
monthly_sales = df.groupby('Month')['Total Sales'].sum().reset_index()
best_month = monthly_sales.idxmax()
max_sales = monthly_sales.max()
#print(f"The best month for sales was month {best_month} with total sales of ${max_sales:.2f}")
monthly_sales.head()

   Month  Total Sales
0      1   1821413.16
1      2   2200078.08
2      3   2804973.35
3      4   3389217.98
4      5   3150616.23

In [ ]:
fig = px.bar(monthly_sales, x='Month' , y='Total Sales')
fig.show()

## Summary of Monthly Sales Analysis

The analysis of monthly sales data revealed a clear trend in customer purchasing behavior throughout the year.

- **Best Performing Month**: December emerged as the best month for sales, achieving a total of **$4,613,443.34** in sales. This could be attributed to holiday shopping or end-of-year promotions.

### Identify Top-Selling Products

In [ ]:
top_selling_products =df.groupby('Product')['Total Sales'].sum().reset_index()
top_selling_products = top_selling_products.sort_values(by='Total Sales',ascending = False)
best_product = top_selling_products.iloc[0]['Product']
max_sales = top_selling_products.iloc[0]['Total Sales']
print(f"The best selling product is {best_product} with total sales of ${max_sales:.2f}")
top_selling_products.head(10)

The best selling product is Macbook Pro Laptop with total sales of $4625700.00

                       Product  Total Sales
13          Macbook Pro Laptop   4625700.00
18                      iPhone   2823100.00
14             ThinkPad Laptop   2401975.98
9                 Google Phone   1965600.00
1       27in 4K Gaming Monitor   1412933.77
3       34in Ultrawide Monitor   1387723.48
6     Apple Airpods Headphones   1361700.00
8                Flatscreen TV    858900.00
7   Bose SoundSport Headphones    777222.27
2             27in FHD Monitor    658756.08

### Worst Performing Products

In [ ]:
worst_product = top_selling_products.iloc[-1]['Product']
min_sales = top_selling_products.iloc[-1]['Total Sales']
print(f"The worst performing product is {worst_product} with total sales of ${min_sales:.2f}")
top_selling_products.tail(10)

The worst performing product is AAA Batteries (4-pack) with total sales of $53338.61

                     Product  Total Sales
2           27in FHD Monitor    658756.08
16           Vareebadd Phone    495600.00
0               20in Monitor    264635.94
10                  LG Dryer    236400.00
11        LG Washing Machine    235800.00
12  Lightning Charging Cable    200793.45
15      USB-C Charging Cable    165746.50
17          Wired Headphones    142141.45
4      AA Batteries (4-pack)     62296.32
5     AAA Batteries (4-pack)     53338.61

### Total Units Sold

In [ ]:
product_units_ordered = df.groupby('Product')['Quantity Ordered'].sum().reset_index()
product_units_ordered = product_units_ordered.sort_values(by='Quantity Ordered', ascending=False)
print("Total units ordered for each product:")
display(product_units_ordered.head(10))

Total units ordered for each product:

                       Product  Quantity Ordered
5       AAA Batteries (4-pack)             17839
4        AA Batteries (4-pack)             16223
15        USB-C Charging Cable             13870
12    Lightning Charging Cable             13431
17            Wired Headphones             11855
6     Apple Airpods Headphones              9078
7   Bose SoundSport Headphones              7773
2             27in FHD Monitor              4392
18                      iPhone              4033
3       34in Ultrawide Monitor              3652

In [ ]:
fig1 = px.bar(product_units_ordered, y='Quantity Ordered', x='Product', text_auto='.2s',
            title="Total Units Ordered")
fig1.update_traces(textfont_size=12, textangle=0, textposition="outside", cliponaxis=False)
fig1.show()

### Plot total units ordered vs. total sales for each product

In [ ]:
merged_product_data = pd.merge(product_units_ordered, top_selling_products, on='Product')
merged_product_data.head(10)

                      Product  Quantity Ordered  Total Sales
0      AAA Batteries (4-pack)             17839     53338.61
1       AA Batteries (4-pack)             16223     62296.32
2        USB-C Charging Cable             13870    165746.50
3    Lightning Charging Cable             13431    200793.45
4            Wired Headphones             11855    142141.45
5    Apple Airpods Headphones              9078   1361700.00
6  Bose SoundSport Headphones              7773    777222.27
7            27in FHD Monitor              4392    658756.08
8                      iPhone              4033   2823100.00
9      34in Ultrawide Monitor              3652   1387723.48

In [ ]:
fig = go.Figure(data=[
    go.Bar(name='Quantity Ordered', x=merged_product_data['Product'], y=merged_product_data['Quantity Ordered']),
    go.Bar(name='Total Sales', x=merged_product_data['Product'], y=merged_product_data['Total Sales'])
])

fig.update_layout(barmode='group',
                  title='Quantity Ordered vs. Total Sales by Product',
                  xaxis_title='Product',
                  yaxis_title='Value')

fig.show()

# Sales Data Analysis Project

This notebook performs a comprehensive analysis of sales data to extract key insights, identify trends, and evaluate product performance. The process includes data loading, cleaning, preprocessing, feature engineering, and exploratory data analysis (EDA).

## Project Summary for Resume

**Sales Data Analyst**

- **Project Focus**: Performed end-to-end sales data analysis on a retail dataset to identify key performance indicators and actionable insights.
- **Data Cleaning & Preprocessing**: Handled missing values, removed duplicates, and performed data type conversions (e.g., `Order Date` to `datetime`, `Quantity Ordered` to `int`, `Price Each` to `float`).
- **Feature Engineering**: Created new features such as `Total Sales` (Quantity Ordered * Price Each), `Month` from `Order Date`, and extracted `Date` and `Time` components.
- **Exploratory Data Analysis (EDA)**:
    - Analyzed monthly sales trends, identifying **December as the best-performing month** (with sales exceeding $4.6 million).
    - Identified **top-selling products** (e.g., Macbook Pro Laptop) and **worst-performing products** (e.g., AAA Batteries).
    - Visualized the relationship between `Quantity Ordered` and `Total Sales` for each product to understand sales dynamics.
- **Tools & Technologies**: Pandas for data manipulation, Plotly Express and Plotly Graph Objects for interactive visualizations.